{"status": "failed", "name": "`percentileCont()` failing on bad arguments -- @1.3 ", "parameters": [{"name": "percentile", "value": "1.1"}], "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "FunctionsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486024850, "historyId": "4553fbff4c939bcb5255052d068e7ccd", "start": 1578486024635, "steps": [{"status": "passed", "start": 1578486024637, "stop": 1578486024840, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486024840, "stop": 1578486024843, "name": "And having executed", "attachments": [{"source": "6c91b094-178c-4848-ba39-3915d6e21052-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486024843, "stop": 1578486024844, "name": "And parameters are", "attachments": [{"source": "331fca8f-cc2b-4741-80a3-ee2bbde91078-attachment.csv", "type": "text/csv", "name": ".table"}]}, {"status": "passed", "start": 1578486024845, "stop": 1578486024847, "name": "When executing query", "attachments": [{"source": "ad5065dc-2963-4852-a300-9a54b49c008a-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "start": 1578486024848, "stop": 1578486024849, "name": "Then a ArgumentError should be raised at runtime: NumberOutOfRange", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 106, in step_impl\n    assert exception != None\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 106, in step_impl\n    assert exception != None\n"}, "uuid": "d7cf2a58-c8cf-4b9b-a292-0fbc98dc7b86"}