{"status": "broken", "name": "`exists()` with literal maps -- @1.3 ", "parameters": [{"name": "map", "value": "{notName: 0, notName2: null}"}, {"name": "result", "value": "false"}], "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "FunctionsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486022268, "historyId": "a564b327b2c6a4f3bba5f04b88214bcb", "start": 1578486022063, "steps": [{"status": "passed", "start": 1578486022063, "stop": 1578486022261, "name": "Given any graph"}, {"status": "passed", "start": 1578486022262, "stop": 1578486022265, "name": "When executing query", "attachments": [{"source": "588e5acd-82c9-442a-afd0-76dad06b9d38-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "c941fc4f-c6d0-482a-8269-e8d0ca381df7-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486022267, "start": 1578486022265, "statusDetails": {"message": "ResponseError: Maps are not currently supported outside of node and relation patterns.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486022268, "stop": 1578486022268, "name": "And no side effects"}], "statusDetails": {"message": "ResponseError: Maps are not currently supported outside of node and relation patterns.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "8a29ef39-bb24-4598-979f-1dc94583d961"}