{"status": "broken", "name": "Matching with LIMIT and optionally matching using a relationship that is already bound", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "MatchAcceptance2"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486071422, "historyId": "68be757a6704603978e44f595d01c4a2", "start": 1578486071313, "steps": [{"status": "passed", "start": 1578486071314, "stop": 1578486071419, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486071419, "stop": 1578486071420, "name": "And having executed", "attachments": [{"source": "4c363167-10a0-4337-8648-433d8fe2afbe-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486071420, "stop": 1578486071421, "name": "When executing query", "attachments": [{"source": "697633d1-1ba2-42a6-959d-440fc9584d2e-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "c9713820-2fbf-4644-aa3b-c8e137e08bc9-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486071421, "start": 1578486071421, "statusDetails": {"message": "ResponseError: RedisGraph does not support OPTIONAL MATCH.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486071422, "stop": 1578486071422, "name": "And no side effects"}], "statusDetails": {"message": "ResponseError: RedisGraph does not support OPTIONAL MATCH.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "cddb77e0-033c-40bd-83ed-56f57ef64b57"}