{"status": "broken", "name": "Handle dependencies across WITH with SKIP", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "crash"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "WithAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486184941, "historyId": "466ed7a25a6a5576d08d29f1bc036138", "start": 1578486184443, "steps": [{"status": "passed", "start": 1578486184443, "stop": 1578486184550, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486184551, "stop": 1578486184940, "name": "And having executed", "attachments": [{"source": "8ed474c2-a06a-4723-940b-4f5248cb00a5-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486184940, "stop": 1578486184941, "name": "When executing query", "attachments": [{"source": "1811edaf-b85b-475e-8164-2a9d8f93fc9c-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "39c226dc-a477-43a3-abf0-c493f0996251-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486184941, "start": 1578486184941, "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486184941, "stop": 1578486184941, "name": "And no side effects"}], "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "0fbfedd8-aeca-402b-814c-12794835dac9"}