{"status": "failed", "name": "`properties()` failing on an integer literal", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "FunctionsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486020734, "historyId": "e8755303bb046c1953f29b3a7e71b5e2", "start": 1578486020611, "steps": [{"status": "passed", "start": 1578486020614, "stop": 1578486020728, "name": "Given any graph"}, {"status": "passed", "start": 1578486020729, "stop": 1578486020732, "name": "When executing query", "attachments": [{"source": "9a97e06b-4ddc-4ec7-affa-20f343d72781-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "start": 1578486020732, "stop": 1578486020733, "name": "Then a SyntaxError should be raised at compile time: InvalidArgumentType", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 135, in step_impl\n    assert \"Type mismatch\" in exception.message\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 135, in step_impl\n    assert \"Type mismatch\" in exception.message\n"}, "uuid": "4dad620d-8379-4fe6-9a89-26c51601d310"}