{"status": "failed", "name": "Failing for `size()` on paths", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "SemanticErrorAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486142019, "historyId": "40cf53f707deb9069608534bf369c883", "start": 1578486141890, "steps": [{"status": "passed", "start": 1578486141892, "stop": 1578486142012, "name": "Given any graph"}, {"status": "passed", "start": 1578486142013, "stop": 1578486142016, "name": "When executing query", "attachments": [{"source": "49c31145-008c-438c-a804-f106636c1e7e-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "failed", "start": 1578486142017, "stop": 1578486142018, "name": "Then a SyntaxError should be raised at compile time: InvalidArgumentType", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 134, in step_impl\n    assert exception != None\n"}}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 134, in step_impl\n    assert exception != None\n"}, "uuid": "a900d542-db31-46ec-ab52-f71f037a032d"}