{"status": "broken", "name": "Mixing MERGE with CREATE", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "MergeRelationshipAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486094078, "historyId": "9ffbb52eaa98b666fab320027100ecd5", "start": 1578486093858, "steps": [{"status": "passed", "start": 1578486093860, "stop": 1578486094071, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486094072, "stop": 1578486094075, "name": "When executing query", "attachments": [{"source": "7d55b026-c377-4df0-8e81-fe2794dc32e7-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "a4635202-876a-4ff3-878b-6cba21082836-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486094077, "start": 1578486094075, "statusDetails": {"message": "ResponseError: RedisGraph does not support queries of the form CREATE...MERGE...CREATE without a separating WITH clause.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486094078, "stop": 1578486094078, "name": "And the side effects should be", "attachments": [{"source": "f289140d-8995-4477-a496-29d24f121986-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "ResponseError: RedisGraph does not support queries of the form CREATE...MERGE...CREATE without a separating WITH clause.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "a9f2f1ac-f01d-48d2-9ffc-1d30382a1ee3"}