{"status": "broken", "name": "Use dynamic property lookup based on parameters when there is lhs type information", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "ExpressionAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486018457, "historyId": "683665355fe5cb2f095833f02ef25d20", "start": 1578486018241, "steps": [{"status": "passed", "start": 1578486018244, "stop": 1578486018448, "name": "Given any graph"}, {"status": "passed", "start": 1578486018449, "stop": 1578486018450, "name": "And parameters are", "attachments": [{"source": "e9435c16-1ed7-4734-8674-d937dca4fcb7-attachment.csv", "type": "text/csv", "name": ".table"}]}, {"status": "passed", "start": 1578486018451, "stop": 1578486018453, "name": "When executing query", "attachments": [{"source": "a42905c0-7031-4149-9d4c-e53adf560e8e-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "d015a3ba-f653-4082-83fe-364d97d731ab-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486018455, "start": 1578486018454, "statusDetails": {"message": "ResponseError: Type mismatch: expected List but was Node\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486018456, "stop": 1578486018456, "name": "And the side effects should be", "attachments": [{"source": "10409ae2-7848-4170-9e5d-a77351182065-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "ResponseError: Type mismatch: expected List but was Node\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "3cebfd8d-048a-4d9f-9038-1a09ca7a4fd3"}