{"status": "broken", "name": "Adding a single label", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "LabelsAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486031086, "historyId": "8d2b9295bc340b148b84756cf52f7287", "start": 1578486030858, "steps": [{"status": "passed", "start": 1578486030860, "stop": 1578486031076, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486031077, "stop": 1578486031079, "name": "And having executed", "attachments": [{"source": "df787b54-a713-437d-a53a-119b36c0c209-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486031079, "stop": 1578486031082, "name": "When executing query", "attachments": [{"source": "d47dab93-adec-4707-a3b8-9b3309e04c11-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "cd56e00d-b3c5-4314-95e5-5bee58f04170-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486031085, "start": 1578486031082, "statusDetails": {"message": "ResponseError: RedisGraph does not currently support set labels\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486031085, "stop": 1578486031086, "name": "And the side effects should be", "attachments": [{"source": "ada1767c-2d6e-41c9-a74e-4aa642c97ffa-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "ResponseError: RedisGraph does not currently support set labels\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "d7a335fd-8922-4bbd-bcc5-dd4c9710549d"}