{"status": "failed", "name": "Undirected expand followed by delete and count", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "DeleteAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486010949, "historyId": "1de90c23a205ee9d1cfd52b678fa6a6e", "start": 1578486010736, "steps": [{"status": "passed", "start": 1578486010738, "stop": 1578486010936, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486010937, "stop": 1578486010940, "name": "And having executed", "attachments": [{"source": "bee0e45e-ac84-4a70-b641-ff038668eba9-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486010940, "stop": 1578486010944, "name": "When executing query", "attachments": [{"source": "d58e93bd-b7df-460e-aaa5-1b7ca0076568-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486010945, "stop": 1578486010946, "name": "Then the result should be", "attachments": [{"source": "6e34cbb0-4334-4430-9d28-97a54e42db63-attachment.csv", "type": "text/csv", "name": ".table"}]}, {"status": "failed", "attachments": [{"source": "3d59bc3e-6b18-4054-a799-182a14a92d28-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486010948, "start": 1578486010946, "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 75, in step_impl\n    assertions.assert_statistics(resultset, stat, value)\n  File \"/home/laptop-linux/dev/redis/graph/tests/tck/features/steps/../../utils/assertions.py\", line 183, in assert_statistics\n    assert(False)\n"}, "name": "And the side effects should be"}], "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 75, in step_impl\n    assertions.assert_statistics(resultset, stat, value)\n  File \"/home/laptop-linux/dev/redis/graph/tests/tck/features/steps/../../utils/assertions.py\", line 183, in assert_statistics\n    assert(False)\n"}, "uuid": "992a865c-72af-4b9f-82d3-c3febb7554fb"}