{"status": "broken", "name": "Multiple aliasing and backreferencing", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "ReturnAcceptance2"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486134284, "historyId": "c0c649c85d60707af396b533722ec88b", "start": 1578486134074, "steps": [{"status": "passed", "start": 1578486134076, "stop": 1578486134278, "name": "Given any graph"}, {"status": "passed", "start": 1578486134278, "stop": 1578486134281, "name": "When executing query", "attachments": [{"source": "11bee7aa-bfe2-4db5-a489-b847232c19d1-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "f322188e-c682-48a2-b020-ae46ae5d166e-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486134283, "start": 1578486134282, "statusDetails": {"message": "ResponseError: Maps are not currently supported outside of node and relation patterns.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486134284, "stop": 1578486134284, "name": "And the side effects should be", "attachments": [{"source": "82c30878-645a-4917-af90-bbe3d03e1ebd-attachment.csv", "type": "text/csv", "name": ".table"}]}], "statusDetails": {"message": "ResponseError: Maps are not currently supported outside of node and relation patterns.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "dd518129-842c-426f-9431-6326055b59a7"}