{"status": "broken", "name": "Match both incoming and outgoing relationships when direction unspecified", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "skip"}, {"name": "feature", "value": "MergeRelationshipAcceptance"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython2"}], "stop": 1578486095259, "historyId": "e005b0ba6285c7b328eeae751c9d4284", "start": 1578486095061, "steps": [{"status": "passed", "start": 1578486095061, "stop": 1578486095170, "name": "Given an empty graph"}, {"status": "passed", "start": 1578486095171, "stop": 1578486095174, "name": "And having executed", "attachments": [{"source": "717664b9-5133-465f-8009-046d84e99c7b-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "passed", "start": 1578486095175, "stop": 1578486095258, "name": "When executing query", "attachments": [{"source": "e9fb21a0-ce3c-4b3d-ad48-155e2dc5a904-attachment.txt", "type": "text/plain", "name": ".text"}]}, {"status": "broken", "attachments": [{"source": "897c1458-871d-4903-9c05-398e7dfb5d97-attachment.csv", "type": "text/csv", "name": ".table"}], "stop": 1578486095259, "start": 1578486095258, "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "name": "Then the result should be"}, {"status": "skipped", "start": 1578486095259, "stop": 1578486095259, "name": "And no side effects"}], "statusDetails": {"message": "ConnectionError: Error 111 connecting to localhost:6379. Connection refused.\n", "trace": "  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/laptop-linux/.local/lib/python2.7/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/Steps.py\", line 84, in step_impl\n    raise exception\n"}, "uuid": "45c038db-10a1-44a2-a137-a3e3ca4b603c"}